# Building Gloabal Automotive Sales Analysis model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings("ignore")

In [5]:
# importing dataset
data = pd.read_csv("../data/bmw_global_sales_2018_2025.csv")
data.head(5)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.5,1.0
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.5,1.0

BEV_Share: Battery Electric Vehicle penetration percentage (0–1 scale).

Premium_Share: BMW’s estimated share within the premium automotive segment in that region.

GDP_Growth: Regional GDP growth rate (%).

Fuel_Price_Index: Relative fuel cost index.

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3072 non-null   int64
 1   Month             3072 non-null   int64
 2   Region            3072 non-null   object
 3   Model             3072 non-null   object
 4   Units_Sold        3072 non-null   int64
 5   Avg_Price_EUR     3072 non-null   int64
 6   Revenue_EUR       3072 non-null   int64
 7   BEV_Share         3072 non-null   float64
 8   Premium_Share     3072 non-null   float64
 9   GDP_Growth        3072 non-null   float64
 10  Fuel_Price_Index  3072 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 264.1+ KB

In [7]:
# missing values
data.isnull().sum()

Year                0
Month               0
Region              0
Model               0
Units_Sold          0
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

In [8]:
# check for duplicates
data.duplicated().sum()

np.int64(0)

In [9]:
data.shape

(3072, 11)

In [10]:
for col in data.columns:
    print(f"{col}: {data[col].nunique()} unique values")

Year: 8 unique values
Month: 12 unique values
Region: 4 unique values
Model: 8 unique values
Units_Sold: 2688 unique values
Avg_Price_EUR: 2924 unique values
Revenue_EUR: 3072 unique values
BEV_Share: 225 unique values
Premium_Share: 309 unique values
GDP_Growth: 242 unique values
Fuel_Price_Index: 49 unique values

In [12]:
for col in data.columns:
    print(f"unique values in {col}: {data[col].unique()}")

unique values in Year: [2018 2019 2020 2021 2022 2023 2024 2025]
unique values in Month: [ 1  2  3  4  5  6  7  8  9 10 11 12]
unique values in Region: ['Europe' 'China' 'USA' 'RestOfWorld']
unique values in Model: ['3 Series' '5 Series' 'X3' 'X5' 'X7' 'i4' 'iX' 'MINI']
unique values in Units_Sold: [ 7822 10280  3105 ...  4906  7871  6732]
unique values in Avg_Price_EUR: [47482 61685 58433 ... 63437 73867 41811]
unique values in Revenue_EUR: [371404204 634121800 181434465 ... 311221922 581407157 281471652]
unique values in BEV_Share: [ 0.011  0.019  0.022  0.021  0.035  0.016  0.013  0.015  0.014  0.017
  0.02   0.009  0.007  0.031  0.01   0.004  0.026  0.029 -0.     0.012
  0.018  0.023  0.03   0.028  0.008  0.034  0.003  0.045  0.025  0.032
  0.033  0.039  0.027  0.024  0.04   0.002  0.041  0.052  0.005  0.006
 -0.001  0.001  0.036 -0.015 -0.002  0.044 -0.005  0.038 -0.003  0.043
 -0.007  0.037  0.046  0.056  0.058  0.051  0.055  0.042  0.048  0.05
  0.054  0.069  0.047  0.062  0.049  0.057  0.053  0.06   0.063  0.064
  0.067  0.061  0.07   0.066  0.071  0.059  0.065  0.084  0.101  0.078
  0.082  0.074  0.075  0.077  0.076  0.072  0.073  0.079  0.068  0.081
  0.085  0.08   0.083  0.086  0.087  0.09   0.094  0.089  0.088  0.091
  0.092  0.098  0.112  0.105  0.095  0.108  0.104  0.102  0.1    0.107
  0.097  0.114  0.096  0.093  0.119  0.109  0.11   0.103  0.099  0.115
  0.106  0.113  0.12   0.116  0.118  0.135  0.122  0.123  0.117  0.137
  0.121  0.141  0.133  0.124  0.126  0.144  0.125  0.136  0.128  0.127
  0.138  0.132  0.111  0.129  0.13   0.131  0.139  0.14   0.143  0.145
  0.134  0.146  0.154  0.148  0.155  0.147  0.151  0.156  0.142  0.166
  0.15   0.16   0.152  0.157  0.159  0.149  0.171  0.161  0.153  0.176
  0.168  0.162  0.17   0.158  0.164  0.173  0.167  0.165  0.177  0.188
  0.18   0.178  0.186  0.184  0.181  0.198  0.175  0.169  0.172  0.174
  0.185  0.191  0.189  0.163  0.182  0.183  0.179  0.197  0.187  0.199
  0.192  0.19   0.193  0.194  0.206  0.195  0.21   0.2    0.201  0.207
  0.205  0.204  0.214  0.211  0.196  0.202  0.203  0.213  0.218  0.212
  0.209  0.208  0.215  0.217  0.223]
unique values in Premium_Share: [19.12 17.6  20.49  6.28 15.6  20.6  15.66  6.87 19.96 15.71 15.88  6.73
 14.6  15.96 14.11  5.64 19.26 18.94 15.74  5.15 17.17 20.05 20.14  5.52
 14.62 17.58 16.36  6.45 18.77 17.66 18.34  6.43 15.16 20.39 19.6   5.51
 16.95 19.19 18.66 15.3  19.22 18.31  5.09 20.78 15.82 18.76  6.08 19.31
 16.25 17.37  6.5  20.1  17.04 18.18  6.3  16.5  18.8   6.8  17.63 18.32
 19.64  6.62 17.12 16.27 18.7   6.86 19.35 14.41 16.57  6.1  14.27 17.85
 14.31  5.11 18.2   6.14 14.35 15.09 15.59  5.66 20.75 20.77 19.73  5.7
 14.48 14.29 14.34  6.03 20.35  6.48 17.8  14.05 14.91  6.93 16.47 17.19
 18.43  6.15 15.31 14.38 17.46  6.54 17.65 19.81  5.29 17.21 18.89 16.82
  5.44 15.45 20.67  5.69 18.93 16.19 19.49  5.41 20.63 17.49 18.25  6.75
 20.13 14.74 14.89 19.1   5.37 18.58 20.31 16.16 14.13 15.72 20.57  5.31
 20.58 17.87 18.71 15.12 15.64 14.82 15.56  6.31 17.76 18.74  6.51 18.88
 14.36  5.34 17.3  15.58 17.38  6.05 14.72 15.24 19.11  5.1  16.32 20.9
 15.5   5.39 19.74 14.56 18.52 17.59  6.19 20.04 19.36  5.49 19.94 16.14
 14.85  6.72 19.71 17.07 20.54  5.55 19.66 15.26 18.07  6.49 14.44 15.92
  5.96 14.59 17.2  20.19  5.5  15.41 17.96 20.51  5.46 20.37 17.29  5.57
 20.56 14.63  6.64 19.89 17.11  5.61 15.14 20.79 18.12  6.95 16.78 17.5
  5.45 19.33 18.17  5.76 14.24 15.01 14.2   5.26 20.81 19.53  6.53 14.93
 16.93 20.36  6.42 19.14 18.47 16.61  5.48 16.81 19.18 14.68  6.9  16.22
 20.3  15.8   5.28 19.42 14.15  5.82 19.21 15.89  6.89 17.4  19.07 20.22
 20.95 14.79 17.64 18.19 20.71  6.02 16.04 20.69  5.65 17.54 15.08 15.11
 18.9   6.   19.28 17.39  6.79 17.1  15.87 14.7   5.56 16.13 20.97  5.81
 19.85 16.86 14.51 14.77 16.84 19.86  6.29 19.75 19.79  6.37 15.84 19.47
  5.97 16.03 19.13 15.2   5.23 15.93 14.81 19.51 15.17  5.35 20.73  5.67
 15.22 18.81 16.87 14.87 16.37 14.86 16.79  5.16 14.33 17.62 20.94  5.85
 14.84 15.19 17.72 17.27 16.45 15.48 20.15 18.91  5.89]
unique values in GDP_Growth: [3.5  2.37 0.82 4.18 4.48 2.66 4.14 2.08 3.92 1.63 2.05 3.52 3.55 3.95
 2.68 2.51 2.78 3.32 3.84 1.67 2.89 5.06 2.99 2.18 3.58 0.99 2.4  3.54
 3.34 4.33 2.67 2.56 1.64 4.22 3.33 5.28 4.62 5.08 2.93 4.36 3.87 3.46
 2.5  1.25 3.75 2.44 1.15 4.25 3.26 4.81 3.57 4.57 2.31 4.4  2.52 2.9
 3.98 2.53 2.98 3.44 2.38 2.25 2.62 5.46 2.79 2.01 3.68 1.92 1.93 1.71
 2.55 2.63 3.91 3.37 2.29 4.31 4.   2.81 4.05 3.19 3.11 2.42 3.45 2.26
 0.65 2.96 1.74 4.66 3.08 5.11 3.27 2.49 3.72 3.39 1.69 2.16 3.01 3.89
 2.41 3.42 2.46 1.48 2.22 3.16 1.5  4.02 3.65 4.71 2.58 4.49 3.71 2.73
 1.86 4.37 1.24 3.24 4.12 3.21 3.85 4.52 1.77 2.47 4.59 4.2  4.53 2.8
 1.79 3.99 1.91 3.2  2.7  1.9  3.53 1.97 1.33 3.43 2.   3.23 3.   3.77
 2.86 4.5  1.61 2.39 3.7  3.18 3.05 3.51 1.7  3.94 1.41 3.31 2.2  3.28
 4.41 3.17 1.47 3.96 2.48 2.43 4.21 3.93 2.6  2.59 3.07 1.14 2.69 0.1
 2.64 4.17 3.76 1.85 3.49 2.28 1.18 3.81 1.31 4.44 4.51 2.82 2.54 3.03
 4.6  3.4  3.22 1.95 2.75 1.94 3.1  4.76 4.47 5.17 1.27 4.9  1.42 3.74
 4.09 1.78 2.65 1.89 2.84 5.12 2.92 2.12 3.6  3.67 4.77 4.26 2.13 5.82
 4.1  3.25 3.38 3.86 3.9  2.85 0.97 1.72 1.84 4.01 2.76 2.94 4.19 4.65
 2.3  2.87 5.25 3.66 4.46 3.59 2.17 3.12 2.09 1.29 1.45 1.07 0.28 5.43
 4.06 4.15 2.21 2.72]
unique values in Fuel_Price_Index: [1.   1.02 0.97 0.98 1.05 0.99 0.96 1.04 1.01 1.03 1.06 0.94 0.93 0.92
 1.07 1.08 1.11 1.09 1.1  1.15 1.13 1.12 1.16 1.14 1.17 1.19 1.2  1.18
 1.23 1.21 1.22 1.27 1.24 1.25 1.26 1.31 1.29 1.28 1.33 1.34 1.32 1.35
 1.3  1.39 1.38 1.36 1.37 1.41 1.4 ]

In [13]:
data.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [14]:
data.dtypes

Year                  int64
Month                 int64
Region               object
Model                object
Units_Sold            int64
Avg_Price_EUR         int64
Revenue_EUR           int64
BEV_Share           float64
Premium_Share       float64
GDP_Growth          float64
Fuel_Price_Index    float64
dtype: object

In [15]:
data.head(3)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0

In [16]:
data['Date'] = pd.to_datetime(data[['Year','Month']].assign(DAY=1))
data.head(3)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index,Date
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.5,1.0,2018-01-01
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.5,1.0,2018-01-01
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.5,1.0,2018-01-01

In [17]:
data.groupby('Date')['Units_Sold'].sum()

Date
2018-01-01    230195
2018-02-01    201033
2018-03-01    250912
2018-04-01    249552
2018-05-01    218362
               ...
2025-08-01    260474
2025-09-01    306776
2025-10-01    237864
2025-11-01    285728
2025-12-01    299002
Name: Units_Sold, Length: 96, dtype: int64

In [ ]:
# Convert price to float
data['Avg_Price_EUR'] = data['Avg_Price_EUR'].astype(float)
data.head(5)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index,Date
0,2018,1,Europe,3 Series,7822,47482.0,371404204.0,0.011,19.12,3.5,1.0,2018-01-01
1,2018,1,Europe,5 Series,10280,61685.0,634121800.0,0.019,19.12,3.5,1.0,2018-01-01
2,2018,1,Europe,X3,3105,58433.0,181434465.0,0.022,19.12,3.5,1.0,2018-01-01
3,2018,1,Europe,X5,7420,67955.0,504226100.0,0.021,19.12,3.5,1.0,2018-01-01
4,2018,1,Europe,X7,8474,92300.0,782150200.0,0.035,19.12,3.5,1.0,2018-01-01

In [20]:
# convert months into months name
data['Month'] = pd.to_datetime(data['Month'], format='%m').dt.month_name()
data.head(5)

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index,Date
0,2018,January,Europe,3 Series,7822,47482.0,371404204.0,0.011,19.12,3.5,1.0,2018-01-01
1,2018,January,Europe,5 Series,10280,61685.0,634121800.0,0.019,19.12,3.5,1.0,2018-01-01
2,2018,January,Europe,X3,3105,58433.0,181434465.0,0.022,19.12,3.5,1.0,2018-01-01
3,2018,January,Europe,X5,7420,67955.0,504226100.0,0.021,19.12,3.5,1.0,2018-01-01
4,2018,January,Europe,X7,8474,92300.0,782150200.0,0.035,19.12,3.5,1.0,2018-01-01

In [21]:
# save cleaned data
data.to_csv("../data/bmw_global_sales_2018_2025_cleaned.csv", index=False)